"""create_users_table

Revision ID: ecddd4f45eab
Revises: 
Create Date: 2026-06-07 10:22:50.777965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecddd4f45eab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user identifier (UUID v4)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment="User email — nullable for OAuth users who don't share email"),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Phone number with country code e.g. +919876543210'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='Unique username for seller profiles'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Full display name'),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='bcrypt hashed password — NULL for OAuth users'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False = account deactivated by user'),
    sa.Column('is_banned', sa.Boolean(), nullable=False, comment='True = banned by admin'),
    sa.Column('banned_reason', sa.Text(), nullable=True, comment='Admin note explaining why user was banned'),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True, comment='When the ban was applied'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='Consecutive failed login attempts — reset on success'),
    sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True, comment='When last failed login attempt occurred'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this time after too many failures'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False, comment='True after user clicks verification link in email'),
    sa.Column('email_verify_token', sa.String(length=255), nullable=True, comment='Random token sent in verification email'),
    sa.Column('email_verify_token_expires', sa.DateTime(timezone=True), nullable=True, comment='Token expires after 24 hours'),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False, comment='True after user verifies OTP sent to phone'),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True, comment='Random token sent in password reset email'),
    sa.Column('password_reset_token_expires', sa.DateTime(timezone=True), nullable=True, comment='Token expires after 1 hour'),
    sa.Column('oauth_provider', sa.Enum('local', 'google', 'github', name='oauthprovider'), nullable=False, comment='How user registered — local/google/github'),
    sa.Column('google_id', sa.String(length=255), nullable=True, comment="Google's unique user ID from OAuth"),
    sa.Column('github_id', sa.String(length=255), nullable=True, comment="GitHub's unique user ID from OAuth"),
    sa.Column('oauth_avatar_url', sa.String(length=500), nullable=True, comment='Profile picture URL from OAuth provider'),
    sa.Column('role', sa.Enum('customer', 'seller', 'admin', name='userrole'), nullable=False, comment='customer/seller/admin — controls permissions'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='Custom profile picture uploaded to AWS S3'),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True, comment='Used for age verification and personalization'),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'prefer_not_to_say', name='usergender'), nullable=True, comment='Optional — used for personalized recommendations'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When account was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Auto-updates whenever any field changes'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful login timestamp'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='True = user deleted account (soft delete)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='When user deleted their account'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verify_token'), 'users', ['email_verify_token'], unique=False)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_verify_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    
    # Alembic forgets to drop ENUMs — always add manually
    op.execute('DROP TYPE IF EXISTS userrole CASCADE')
    op.execute('DROP TYPE IF EXISTS usergender CASCADE')
    op.execute('DROP TYPE IF EXISTS oauthprovider CASCADE')
